DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Pages;
DROP TABLE IF EXISTS PageContent;

CREATE TABLE IF NOT EXISTS Users (
    ID INTEGER NOT NULL,
    Username TEXT NOT NULL,
    Password BLOB NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Categories (
    ID INTEGER NOT NULL,
    Name TEXT NOT NULL,
    SearchName TEXT NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Pages (
    ID INTEGER NOT NULL,
    CategoryID INTEGER NOT NULL,
    Name TEXT NOT NULL,
    SearchName TEXT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(CategoryID) REFERENCES Categories(ID)
);

CREATE TABLE IF NOT EXISTS PageContent (
    PageID INTEGER NOT NULL,
    Version INTEGER NOT NULL,
    Content TEXT NOT NULL,
    EditedBy INTEGER NOT NULL,
    DateModified DATETIME NOT NULL,
    FOREIGN KEY(PageID) REFERENCES Pages(ID),
    FOREIGN KEY(EditedBy) REFERENCES Users(ID)
);
